name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Flink-Kafka-Consumer/**'

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: mklepium/id2221-flink-kafka-consumer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Needed for running the workflow on different branches
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:latest
          context: Flink-Kafka-Consumer/
          file: Scripts/Deployment/Flink-Dockerfile
          labels: |
            org.opencontainers.image.title=${{ env.IMG_NAME }}
            org.opencontainers.image.source=https://github.com/mklepium/id2221-Data-Intensive-Computing
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


