name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Flink-Kafka-Consumer/**'

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: mklepium/id2221-flink-kafka-consumer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Needed for running the workflow on different branches
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:latest
          context: Flink-Kafka-Consumer/
          file: Scripts/Deployment/Flink-Dockerfile
          labels: |
            org.opencontainers.image.title=${{ env.IMG_NAME }}
            org.opencontainers.image.source=https://github.com/mklepium/id2221-Data-Intensive-Computing
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: SSH and Deploy Docker Container on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          script: |
            cd /opt/Flink-Kafka-Consumer
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ env.IMG_NAME }}:latest
            docker stop my_running_container || true
            docker logs my_running_container > dockerlog_$(date +"%Y_%m_%d_%I_%M_%p").log || true
            docker rm my_running_container || true
            docker run -d --name my_running_container ${{ env.IMG_NAME }}:latest
