name: Deploy Gatherer



on:
  push:
    paths:
      - 'DB/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'DB/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt'  # Specify the remote path where you want to copy your application

            



