name: Deploy Gatherer



on:
  push:
    paths:
      - 'Gatherer/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy application code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'Gatherer/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt'  # Specify the remote path where you want to copy your application

      - name: Kill Previous Process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          script: |
            pkill -f "python data_gatherer.py" || true  # Terminate previous process if it exists

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/Gatherer
            nohup python data_gatherer.py > app.log 2>&1 &



