name: Deploy Gatherer

on:
  push:
    paths:
      - 'Gatherer/**'

jobs:
  build:
    name: Gatherer, Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: mklepium/id2221-gatherer
    
    steps:
      - name: Gatherer, Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Needed for running the workflow on different branches

      - name: Gatherer, Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Gatherer, Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Gatherer, Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMG_NAME }}:latest
          context: .
          file: Scripts/Deployment/Gatherer-Dockerfile
          labels: |
            org.opencontainers.image.title=${{ env.IMG_NAME }}
            org.opencontainers.image.source=https://github.com/mklepium/id2221-Data-Intensive-Computing

      - name: Gatherer, SSH and Deploy Docker Container on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          script: |
            cd /opt/Gatherer
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ env.IMG_NAME }}:latest
            docker stop Gatherer || true
            docker logs Gatherer > dockerlog_$(date +"%Y_%m_%d_%I_%M_%p").log || true
            docker rm Gatherer || true
            docker run --network="host" -e API_KEY="$${{ secrets.API_KEY }}" -d --name gatherer ${{ env.IMG_NAME }}:latest
