name: Deploy Kafka

on:
  push:
    paths:
      - 'Kafka/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Config toserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'Kafka/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt'  # Specify the remote path where you want to copy your application

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          # TODO: Change the script to actually use kafka.
          # TODO: Check if permissions are correct.
          # TODO: Not sure if the restart of both is necessary. But for the time it works.
          script: |
            cp /opt/Gatherer/Kafka/server.properties /home/kafka/kafka/config/server.properties
            cp /opt/Gatherer/Kafka/zookeeper.properties /home/kafka/kafka/config/zookeeper.properties 
            sudo systemctl restart zookeeper
            sudo systemctl restart kafka

            




