name: Deploy test

on:
  push:
    paths:
      - 'Gatherer/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy application code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use SSH key for security if possible
          port: ${{ secrets.SERVER_PORT }}
          source: 'Gatherer/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt/gatherer'  # Specify the remote path where you want to copy your application

