name: Deploy Kafka

on:
  push:
    paths:
      - 'Kafka/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy application code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'Kafka/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt/Gatherer'  # Specify the remote path where you want to copy your application

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          # TODO: Change the script to actually use kafka.
          # TODO: Install Kafka on the server.
          # l39: is used to save the PID of the process to a file.
          script: |
            cd /opt/gatherer/Kafka
            nohup python data_gatherer.py > app.log 2>&1 &
            echo $! > pidfile.txt



