name: Deploy Gatherer



on:
  push:
    paths:
      - 'Gatherer/**'  # Specify the path to your subproject

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy application code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'Gatherer/'  # Specify the path of the /Gatherer folder in your GitHub repo
          target: '/opt'  # Specify the remote path where you want to copy your application

            

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          # Do not ask me why this is so ugly.
          # This was an adventure. So feel free to ask me, because it hurt and I have knowledge to share xd
          script: |
            cd /opt/Gatherer
            echo "test"
            if pgrep -f "python data_gatherer.py" | grep -v "^$$\$"; then pkill -f "python data_gatherer.py"; fi
            echo "test2"
            nohup python data_gatherer.py > app.log 2>&1 &



