name: Deploy Kafka


on:
  push:
    paths:
      - 'Kafka/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Config toserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          source: 'Kafka/'  
          target: '/opt'  

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}  # I missnamed it in GIT
          port: ${{ secrets.SERVER_PORT }}
          # TODO: Not sure if the restart of both is necessary. But for the time it works.
          script: |
            cp /opt/Gatherer/Kafka/server.properties /opt/installed-kafka/config/server.properties
            cp /opt/Gatherer/Kafka/zookeeper.properties /opt/installed-kafka/config/zookeeper.properties 
            sudo systemctl restart zookeeper
            sudo systemctl restart kafka

            




